version: '3.7'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: binance-monitor-api
    container_name: binance-monitor-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
