version: '3.7'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: binance-monitor-api
    container_name: binance-monitor-api
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    entrypoint: /var/www/docker/bin/docker-php-entrypoint.sh
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_NAME: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - my-datavolume:/var/lib/mysql
# stored in /var/lib/docker/volumes
volumes:
  my-datavolume:
